# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: common
    type: github
    name: mksipe/Shell-Script-Lib
  containers:
  - container: linux
    image: ubuntu-16.04
pool:
  vmImage: 'Ubuntu 16.04'
steps:
- script: echo It Works
  displayName: 'Test if echoing a command works'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
